# Generated by Django 5.0.6 on 2024-05-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_image',
            field=models.FileField(blank=True, default=None, max_length=300, null=True, upload_to='company/'),
        ),
    ]
